library(dataRetrieval)
library(tidyverse)
library(zoo)


# Remove exisiting Environment
# Warning - This cannot be undone
rm(list=ls())

# Load Environment as run on 6/15/2018 in the morning.
# This is here beacuse the datapulls take so long to run and 
# it's handy to have it already done
# When we load into AWQWMS, we should delete these lines and run
# It fresh
load("Data Sources/NWISsumstats.Rdata")


# NWIS codes: https://nwis.waterdata.usgs.gov/usa/nwis/pmcodes/help?codes_help
# data retriveal help: https://pubs.usgs.gov/tm/04/a10/pdf/tm4A10_appendix_1.pdf

# list of NWIS sites in oregon
sites <- whatNWISsites(stateCD = "or",
                       hasDataTypeCd=c("dv","uv"))

USGS_stations <- sites$site_no
start.date = "2008-01-01"
end.date = "2018-12-31"
statcds = c("00001", "00002", "00003", "00008")
# 00001 = max, 00002 = min, 00003 = mean, 00008 = median
pCodes = c("00010", "00400", "00300", "00301")
# 00010 = temp, 00400 = ph, 00300 = DO mg/L, 00301 = DO sat

# this will get you all data. Way too big for 10 years data
# my computer runs out of resources to convert from wide to long
# need to run each param seperate
# 
# nwis.sum.stats.temp <- readNWISdv(siteNumbers = USGS_stations,
#                              parameterCd = pCodes,
#                              startDate = start.date,
#                              endDate = end.date,
#                              statCd = statcds)

# nwis.sum.stats <- renameNWISColumns(nwis.sum.stats)


# NWIS temperature --------------------------------------------------------



nwis.sum.stats.temp <- readNWISdv(siteNumbers = USGS_stations,
                                  parameterCd = "00010",
                                  startDate = start.date,
                                  endDate = end.date,
                                  statCd = statcds)

nwis.sum.stats.temp <- renameNWISColumns(nwis.sum.stats.temp)



# Calculate 7 day moving average
# lag uses 6 because the 7 day moving average is inclusive of the date
# If 1 day is missing from period, do not caluclate average
temp4ma <- nwis.sum.stats.temp %>%
  group_by(site_no) %>%
  mutate(startdate = lag(Date, 6, order_by = Date),
         # flag out which result gets a moving average calculated
         calcma = ifelse(startdate == (Date - 6), 1, 0 )) %>%
  mutate(ma = ifelse(calcma == 1, round(rollmean(x = Wtemp_Max, 7, align = "right", fill = NA),1) , NA ))
 
 

nwis.sum.stats.temp.gather <- temp4ma %>%
  gather(Wtemp_Max, Wtemp, Wtemp_Min, ma, key = "stat", value = "result", na.rm = TRUE) %>%
  mutate(qual = ifelse(stat == "Wtemp_Max" | stat == "ma", Wtemp_Max_cd, 
                       ifelse(stat == "Wtemp", Wtemp_cd, 
                              ifelse(stat == "Wtemp_Min", Wtemp_Min_cd, "ERROR" )))) %>%
  select(agency_cd, site_no, Date, stat, result, qual, startdate) %>%
  arrange(site_no, Date)




nwis.sum.stats.temp.AWQMS <- nwis.sum.stats.temp.gather %>%
  ungroup() %>%
  transmute(CharID = "TEMP",
         Unit = "deg C",
         Method = "THM01",
         RsltType = "Calculated",
         Qualcd = qual,
         StatisticalBasis = ifelse(stat == "ma","7DMADMax",
                                   ifelse(stat == "Wtemp_Max", "Daily Maximum",
                                   ifelse(stat == "Wtemp", "Daily Mean",
                                          ifelse(stat == "Wtemp_Min", "Daily Minimum",
                                                 "ERROR")))),
         RsltTimeBasis = ifelse(StatisticalBasis == "7DMADMax", "7 day", "1 Day" ),
         DEQ_RsltComment = ifelse(StatisticalBasis == "7DMADMax", "Generated by ORDEQ", "" ),
         ActivityType = "FMC",
         SiteID = site_no,
         SmplColMthd = "ContinuousPrb",
         SmplColEquip = "Probe/Sensor",
         SmplDepth = "",
         SmplDepthUnit = "m",
         SmplColEquipComment = "",
         Samplers = "",
         SmplEquipID = site_no,
         Project = "USGS-OR",
         ActStartDate = Date,
         ActStartTime = "0:00",
         ActEndDate = Date,
         ActEndTime = "0:00",
         ActEndTimeZone = "PST",
         AnaStartDate = ifelse(StatisticalBasis == "7DMADMax", startdate, ActStartDate ),
         AnaStartTime = "0:00",
         AnaStartTimeZone = "PST",
         AnaEndDate = Date,
         AnaEndTime = "0:00",
         AnaEndTimeZone = "PST",
         ActComment = "" )


# NWIS pH -----------------------------------------------------------------
# Commenting out due to not using contiuous pH for assessment
# nwis.sum.stats.ph <- readNWISdv(siteNumbers = USGS_stations,
#                                   parameterCd = "00400",
#                                   startDate = start.date,
#                                   endDate = end.date,
#                                   statCd = statcds)
# 
# nwis.sum.stats.ph <- renameNWISColumns(nwis.sum.stats.ph)
# 
# nwis.sum.stats.ph.gather <- nwis.sum.stats.ph %>%
#   gather(pH_Max, pH, pH_Min, key = "stat", value = "result") %>%
#   mutate(qual = ifelse(stat == "pH_Max", pH_Max_cd, 
#                        ifelse(stat == "pH", pH_cd, 
#                               ifelse(stat == "pH_Min", pH_Min_cd, "ERROR" )))) %>%
#   select(agency_cd, site_no, Date, stat, result, qual)

#write_csv(nwis.sum.stats.ph.gather, "nwis_pH_sum_stats_long.csv")




# NWIS DO conc ------------------------------------------------------------

nwis.sum.stats.DO <- readNWISdv(siteNumbers = USGS_stations,
                                parameterCd = "00300",
                                startDate = start.date,
                                endDate = end.date,
                                statCd = statcds)


nwis.sum.stats.DO <- renameNWISColumns(nwis.sum.stats.DO)


# Calculate moving averages. If 1 day is missing from period, do not caluclate average
DO4ma <- nwis.sum.stats.DO %>%
  group_by(site_no) %>%
  mutate(startdate7 = lag(Date, 6, order_by = Date),
         # flag out which result gets a moving average calculated
         calc7ma = ifelse(startdate7 == (Date - 6), 1, 0 ),
         startdate30 = lag(Date, 29, order_by = Date),
         calc30ma = ifelse(startdate30 == (Date - 29), 1, 0 )) %>%
  mutate(ma.mean7 = ifelse(calc7ma == 1, round(rollmean(x = DO, 7, align = "right", fill = NA),1) , NA ),
         ma.mean30 = ifelse(calc30ma == 1, round(rollmean(x = DO, 30, align = "right", fill = NA),1) , NA ),
         ma.min7 = ifelse(calc7ma == 1, round(rollmean(x = DO_Min, 7, align = "right", fill = NA),1) , NA )) 


nwis.sum.stats.DO.gather <- DO4ma %>%
  gather(DO_Max, DO, DO_Min, ma.mean7, ma.mean30,ma.min7,   key = "stat", value = "result", na.rm = TRUE) %>%
  mutate(qual = ifelse(stat == "DO_Max", DO_Max_cd, 
                       ifelse(stat == "DO" | stat == "ma.mean7" | stat == "ma.mean30", DO_cd, 
                              ifelse(stat == "DO_Min" | stat == "ma.min7", DO_Min_cd, "ERROR" )))) %>%
  select(agency_cd, site_no, Date, stat, result, qual, startdate7, startdate30 )


nwis.sum.stats.DO.AWQMS <- nwis.sum.stats.DO.gather %>%
  ungroup() %>%
  transmute(CharID = "DO",
            Unit = "mg/L",
            Method = "LUMIN",
            RsltType = "Calculated",
            Qualcd = qual,
            StatisticalBasis = ifelse(stat == "ma.mean7","7DMADMean",
                                      ifelse(stat == "DO_Max", "Daily Maximum",
                                             ifelse(stat == "DO", "Daily Mean",
                                                    ifelse(stat == "DO_Min", "Daily Minimum",
                                                           ifelse(stat == "ma.mean30", "30DMADMean",
                                                                  ifelse(stat == "ma.min7", "7DMADMin", "ERROR")))))),
            RsltTimeBasis = ifelse(StatisticalBasis == "7DMADMean" | StatisticalBasis == "7DMADMin", "7 day",
                                   ifelse(StatisticalBasis == "30DMADMean", "30 Day", "1 Day" )),
            DEQ_RsltComment = ifelse(StatisticalBasis == "7DMADMean" |
                                       StatisticalBasis == "7DMADMin" |
                                       StatisticalBasis == "30DMADMean", "Generated by ORDEQ", "" ),
            ActivityType = "FMC",
            SiteID = site_no,
            SmplColMthd = "ContinuousPrb",
            SmplColEquip = "Probe/Sensor",
            SmplDepth = "",
            SmplDepthUnit = "m",
            SmplColEquipComment = "",
            Samplers = "",
            SmplEquipID = site_no,
            Project = "USGS-OR",
            ActStartDate = Date,
            ActStartTime = "0:00",
            ActEndDate = Date,
            ActEndTime = "0:00",
            ActEndTimeZone = "PST",
            AnaStartDate = ifelse(StatisticalBasis == "7DMADMax" |StatisticalBasis == "7DMADMin" , startdate7, 
                                  ifelse(StatisticalBasis == "30DMADMean", startdate30, ActStartDate )),
            AnaStartTime = "0:00",
            AnaStartTimeZone = "PST",
            AnaEndDate = Date,
            AnaEndTime = "0:00",
            AnaEndTimeZone = "PST",
            ActComment = "" )


#write_csv(nwis.sum.stats.DO.gather, "nwis_DO_sum_stats_long.csv")



# NWIS DO sat ------------------------------------------------------------
#### There does not appear to be any DO sat data in NWIS for Oregon
# nwis.sum.stats.DOsat <- readNWISdv(siteNumbers = USGS_stations,
#                                 parameterCd = "00301",
#                                 startDate = start.date,
#                                 endDate = end.date,
#                                 statCd = statcds)
# 
# 
# nwis.sum.stats.DOsat <- renameNWISColumns(nwis.sum.stats.DOsat)


# #list of sites from the sum.stats table
# nwis_sum_stat_sites <- unique(nwis.sum.stats$site_no)
# 
# #pull site info from NWIS for sites identified in sum.stats table
# nwis_sites <- readNWISsite(nwis_sum_stat_sites)




# Monitoring station information ------------------------------------------

#read in county query
county_query <- read_csv("county_query.csv", col_types = c(col_character())) %>%
  mutate(county_cd = as.character(county_cd)) %>%
  select(county_cd, county_nm)

nwissites <- unique(c(unique(nwis.sum.stats.DO.AWQMS$SiteID), unique(nwis.sum.stats.temp.AWQMS$SiteID)))

nwissites <- readNWISsite(unique(nwissites))


nwis.sites.AWQMS <- nwissites %>%
  left_join(county_query, by = "county_cd") %>% 
  transmute(Stationkey = site_no,
            Desc = station_nm,
            SiteComments = "",
            MonLocType = ifelse(site_tp_cd == "ST", 'River/Stream', 
                                ifelse(site_tp_cd == "LK", "Lake", 
                                       ifelse(site_tp_cd == "ST-CA", "Canal Transport", 
                                              ifelse(site_tp_cd == "GW", "Well", "ERROR" )))),
            COUNTY = county_nm,
            STATE = "OR",
            Country = "US",
            HUC8 = huc_cd,
            HUC12 = "",
            TribalLand = "",
            TribalName = "",
            CreateDate = "",
            T_R_S = "",
            Lat = dec_lat_va,
            Long = dec_long_va,
            Datum = dec_coord_datum_cd,
            CollMethod = "",
            MapScale = map_scale_fc,
            Comments = "",
            WellType = ifelse(MonLocType == "Well", "Monitoring", ""),
            WellForm = "",
            WellAquiferName = ifelse(MonLocType == "Well", nat_aqfr_cd, ""),
            WellDepth = ifelse(MonLocType == "Well", well_depth_va, ""),
            WellDepthUnit = "ft",
            AltLocID = "",
            AltLocName = "",
            EcoRegion3 = "",
            Reachcode = "",
            GNIS_Name = "",
            AU_ID = ""
            ) 
            
# remove NAs
nwis.sites.AWQMS[is.na(nwis.sites.AWQMS)] <- ""            
            
            



# Write csvs --------------------------------------------------------------


# write_csv(nwis.sum.stats, "nwis_sum_stats_R.csv")
# write_csv(nwis_sites, "nwis_sum_stat_sites_R.csv")


# Cont DO data ------------------------------------------------------------

# 
# cont_DO <- readNWISuv(siteNumbers = unique(nwis.sum.stats.DO$site_no),
#            parameterCd = "00300",
#            startDate = start.date,
#            endDate = end.date)
# 
# cont_DO <- readNWISuv(siteNumbers = "11507501",
#                       parameterCd = "00300",
#                       startDate = start.date,
#                       endDate = end.date,
#                       tz = "UTC")
# cont_DO <-  renameNWISColumns(cont_DO)
