library(tidyverse)
library(readxl)
library(lubridate)
library(openxlsx)
library(zoo)



# Setup -------------------------------------------------------------------

# clean out exisiting environment
# helps to avoid overwriting
rm(list = ls())

# Choose submitted file to generate stats on 
filepath <- file.choose()


# read results tab of submitted file
Results_import <- read_excel(filepath, sheet = "Results")
colnames(Results_import) <- make.names(names(Results_import), unique=TRUE)


# convert F to C, filter out rejected data, and create datetime column
results_data <- Results_import %>%
  mutate(r = ifelse(Result.Unit == "deg F", round((Result.Value - 32)*(5/9),2), Result.Value),
         r_units = ifelse(Result.Unit == "deg F", "deg C", Result.Unit )) %>%
  filter(Result.Status.ID != "Rejected") %>%
  mutate(time_char = strftime(Activity.Start.Time, format = "%H:%M:%S", tz = 'UTC'),
         datetime = ymd_hms(paste(Activity.Start.Date, time_char)))


# get unique list of characteristics to run for loop through
unique_characteritics <- unique(Results_import$Characteristic.Name)

#create list for getting data out of loop
monloc_do_list <- list()
sumstatlist <- list()

# For loop for summary statistics -----------------------------------------


# Loop goes through each characteristc and generates summary stats
# After loop, data gets pushed inot single table
for (i in 1:length(unique_characteritics)){
  
  # Characteristic for this loop iteration
  char <- unique_characteritics[i]
  
  # Filter so table only contains single characteristic
  results_data_char <- results_data %>%
    filter(Characteristic.Name == char) %>%
    # generare unique hour field for hourly values and stats
    mutate(hr =  format(datetime, "%Y-%j-%H"))
  
  # Simplify to hourly values and Stats
  hrsum <- results_data_char %>%
    group_by(Monitoring.Location.ID, Equipment.ID.., hr, r_units, Activity.Start.End.Time.Zone) %>%
    summarise(date = mean(Activity.Start.Date),
              hrDTmin = min(datetime),
              hrDTmax = max(datetime),
              hrN = sum(!is.na(r)),
              hrMean = mean(r, na.rm=TRUE),
              hrMin = min(r, na.rm=TRUE),
              hrMax = max(r, na.rm=TRUE))
 
  
   # For each date, how many hours have hrN > 0
  # remove rows with zero records in an hour. 
  hrdat<- hrsum[which(hrsum$hrN >0),]
  
  # Summarise to daily statistics
  daydat <- hrdat %>%
    group_by(Monitoring.Location.ID, Equipment.ID.., date, r_units, Activity.Start.End.Time.Zone) %>%
    summarise(  dDTmin = min(hrDTmin),
                dDTmax = max(hrDTmax),
                hrNday = length(hrN), 
                dyN = sum(hrN),
                dyMean = mean(hrMean, na.rm=TRUE),
                dyMin = min(hrMin, na.rm=TRUE),
                dyMax = max(hrMax, na.rm=TRUE))
  
  daydat <- daydat %>%
    rowwise() %>%
    mutate(ResultStatusID = ifelse(hrNday >= 22, 'Final', "Rejected")) %>%
    mutate(cmnt =ifelse(hrNday >= 22, "Generated by ORDEQ", ifelse(hrNday <= 22 & hrNday >= 20, 
                                                                  paste0("Generated by ORDEQ; Estimated - ", as.character(hrNday), ' hrs with valid data in day' ), 
                                                                  paste0("Generated by ORDEQ; Rejected - ", as.character(hrNday), ' hrs with valid data in day' )) )) %>%
    mutate(ma.mean7 = as.numeric(""),
           ma.min7 = as.numeric(""),
           ma.mean30 = as.numeric(""),
           ma.max7 = as.numeric(""))
  
  if (results_data_char$Characteristic.Name[1]  %in% c('DO','adjDO','DOs', "Dissolved oxygen (DO)")) {
    
    #monitoring location loop
    for(j in 1:length(unique(daydat$Monitoring.Location.ID))){
      
      station <- unique(daydat$Monitoring.Location.ID)[j]
      
      daydat_station <- daydat %>%
        filter(Monitoring.Location.ID == station) %>%
        mutate(startdate7 = as.Date(date) - 6,
               startdate30 = as.Date(date) -30)
      
     #7 day loop
       for(k in 1:nrow(daydat_station)){
        
         start7 <- daydat_station$startdate7[k]
         end7 <- daydat_station$date[k] 
         
         station_7day <- daydat_station %>%
           filter(date <= end7 & date >= start7) %>%
           filter(hrNday >= 22) 
         
         ma.mean7 <- ifelse(length(unique(station_7day$date)) >= 6, mean(station_7day$dyMean), NA )
         ma.min7 <- ifelse(length(unique(station_7day$date)) >= 6, min(station_7day$dyMean), NA )
         
         daydat_station[k,"ma.mean7"] <- ma.mean7
         daydat_station[k, "ma.min7"] <- ma.min7
         
         
        
        
      } #end of 7day loop
      
    # 30 day loop
      for(l in 1:nrow(daydat_station)){
        
        
        start30 <- daydat_station$startdate30[l]
        end30 <- daydat_station$date[l] 
        
        station_30day <- daydat_station %>%
          filter(date <= end30 & date >= start30) %>%
          filter(hrNday >= 22) 
        
        ma.mean30 <- ifelse(length(unique(station_30day$date)) >= 29, mean(station_30day$dyMean), NA )
   
        
        daydat_station[l,"ma.mean30"] <- ma.mean30
   
      } #end of 30day loop
      
    
      monloc_do_list[[j]] <- daydat_station
      
    } # end of monitoring location for loop
  
    sum_stats <- bind_rows(monloc_do_list)    
    
    } # end of DO if statement
  
  
  ##  TEMPERATURE
  
  if (results_data_char$Characteristic.Name[1] %in% c('TEMP','adjTEMP', 'Temperature, water' )) {
    
    sum_stats <- daydat %>%
      arrange(Monitoring.Location.ID, date) %>%
      group_by(Monitoring.Location.ID) %>%
      mutate(startdate7 = lag(date, 6, order_by = date),
             # flag out which result gets a moving average calculated
             calc7ma = ifelse(startdate7 == (as.Date(date) - 6), 1, 0 ))%>%
      mutate(ma.max7 = ifelse(calc7ma == 1, round(rollmean(x = dyMax, 7, align = "right", fill = NA),2) , NA )) %>%
      select(-startdate7, -calc7ma )
    
  } #end of temp if statement
 
  
  sum_stats <- sum_stats %>%
    mutate(charID = char) 
  
  sumstatlist[[i]] <-  sum_stats
  
  } # end of characteristics for loop



sumstat <- bind_rows(sumstatlist)

























