require(rgdal)
require(RODBC)
require(tidyverse)
require(IRlibrary)
library(lubridate)
library(openxlsx)
library(zoo)

# This script takes as an input the access databases sumbitted by the USFS and gernates a 
# summary statistic file for uploading into AWQMS


# Setup -------------------------------------------------------------------

# clean out exisiting environment
# helps to avoid overwriting
rm(list = ls())



database <- file.choose()

# Database query --------------------------------------------------------


usfs.db <-  odbcConnectAccess2007(database, case="nochange")

Results_import <-
  sqlQuery(
    usfs.db,
    "SELECT NRW_AI_TEMPERATURE_SRVY.NAME, NRW_AI_TEMPERATURE.MEAS_DATE, NRW_AI_TEMPERATURE.TEMPERATURE_STD
FROM NRW_AI_TEMPERATURE INNER JOIN NRW_AI_TEMPERATURE_SRVY ON NRW_AI_TEMPERATURE.HDR_FK = NRW_AI_TEMPERATURE_SRVY.HDR_CN
    ORDER BY NRW_AI_TEMPERATURE_SRVY.NAME, NRW_AI_TEMPERATURE.MEAS_DATE;
    ", as.is = TRUE)


odbcClose(usfs.db)


# Results formatting ------------------------------------------------------


Results <- Results_import %>%
  mutate(datetime = ymd_hms(MEAS_DATE))



# Hourly summaries --------------------------------------------------------

hrsum <- Results %>%
  mutate(hr =  format(datetime, "%Y-%j-%H")) %>%
  group_by(NAME, hr) %>%
  summarise(date = first(as.Date(datetime)),
            hrDTmin = min(datetime),
            hrDTmax = max(datetime),
            hrN = sum(!is.na(TEMPERATURE_STD)),
            hrMean = mean(TEMPERATURE_STD, na.rm=TRUE),
            hrMin = min(TEMPERATURE_STD, na.rm=TRUE),
            hrMax = max(TEMPERATURE_STD, na.rm=TRUE)) 

hrdat<- hrsum[which(hrsum$hrN >0),]


# Daily Summaries ---------------------------------------------------------

daydat <- hrdat %>%
  group_by(NAME, date) %>%
  summarise(  dDTmin = min(hrDTmin),
              dDTmax = max(hrDTmax),
              hrNday = length(hrN), 
              dyN = sum(hrN),
              dyMean = mean(hrMean, na.rm=TRUE),
              dyMin = min(hrMin, na.rm=TRUE),
              dyMax = max(hrMax, na.rm=TRUE))

daydat <- daydat %>%
  rowwise() %>%
  mutate(ResultStatusID = ifelse(hrNday >= 22, 'Final', "Rejected")) %>%
  mutate(cmnt =ifelse(hrNday >= 22, "Generated by ORDEQ", ifelse(hrNday <= 22 & hrNday >= 20, 
                                                                 paste0("Generated by ORDEQ; Estimated - ", as.character(hrNday), ' hrs with valid data in day' ), 
                                                                 paste0("Generated by ORDEQ; Rejected - ", as.character(hrNday), ' hrs with valid data in day' )) )) 

# 7 day moving averages ---------------------------------------------------
sum_stats <- daydat %>%
  arrange(NAME, date) %>%
  group_by(NAME) %>%
  mutate(startdate7 = lag(date, 6, order_by = date),
         # flag out which result gets a moving average calculated
         calc7ma = ifelse(startdate7 == (as.Date(date) - 6), 1, 0 ))%>%
  mutate(ma.max7 = ifelse(calc7ma == 1, round(rollmean(x = dyMax, 7, align = "right", fill = NA),2) , NA )) %>%
  select(-startdate7, -calc7ma )



# Wide to long format ------------------------------------------------------

sumstat_long <- sum_stats %>%
  rename("Daily Maximum" = dyMax,
         "Daily Minimum" = dyMin,
         "Daily Mean"    = dyMean,
         "7DMADMax"      = ma.max7,
         ) %>%
  gather(
    "Daily Maximum",
    "Daily Minimum",
    "Daily Mean",
    "7DMADMax",
    key = "StatisticalBasis",
    value = "Result",
    na.rm = TRUE
  ) %>% 
  arrange(NAME, date) 


# AWQMS formatting --------------------------------------------------------

#Assumptions:
# method is 170.1
# Timezone is PST
# Equipment is station name
# temp is measred in C
# project name is to be determined at import


AQWMS_sum_stat <- sumstat_long %>%
  mutate(RsltTimeBasis = ifelse(StatisticalBasis == "7DMADMin" |
                                  StatisticalBasis == "7DMADMean" |
                                  StatisticalBasis == "7DMADMax", "7 Day", 
                                ifelse(StatisticalBasis == "30DMADMean", "30 Day", "1 Day" )),
         ActivityType = "FMC",
         Result.Analytical.Method.ID = "170.1",
         SmplColMthd = "ContinuousPrb",
         SmplColEquip = "Probe/Sensor",
         SmplDepth = "",
         SmplDepthUnit = "",
         SmplColEquipComment = "",
         Samplers = "",
         Project = "USFS AqS Water Temperature Surveys",
         AnaStartDate = "",
         AnaStartTime = "",
         AnaEndDate = "",
         AnaEndTime = "",
         ActStartDate = format(dDTmin, "%Y-%m-%d"), 
         ActStartTime = format(dDTmin, "%H:%M"),
         ActEndDate = format(dDTmax, "%Y-%m-%d"),
         ActEndTime = format(dDTmax, "%H:%M"),
         RsltType = "Calculated",
         ActStartTimeZone = 'PST',
         ActEndTimeZone = 'PST',
         AnaStartTimeZone = "",
         AnaEndTimeZone = "",
         Result = round(Result, digits = 2),
         charID = "Temperature, water",
         r_units = "deg C",
         Equipment = NAME
  ) %>%
  select(charID,
         Result,
         r_units,
         Result.Analytical.Method.ID,
         RsltType,
         ResultStatusID,
         StatisticalBasis,
         RsltTimeBasis,
         cmnt,
         ActivityType,
         NAME,
         SmplColMthd,
         SmplColEquip,
         SmplDepth,
         SmplDepthUnit,
         SmplColEquipComment,
         Samplers,
         Equipment,
         Project,
         ActStartDate,
         ActStartTime,
         ActStartTimeZone,
         ActEndDate,
         ActEndTime,
         ActEndTimeZone,
         AnaStartDate,
         AnaStartTime,
         AnaStartTimeZone,
         AnaEndDate,
         AnaEndTime,
         AnaEndTimeZone)


# Export to same place as the originial file
openxlsx::write.xlsx(AQWMS_sum_stat, paste0(tools::file_path_sans_ext(database),"-sumstat.xlsx"))
